const SUPABASE_URL="https://nfwesibtnvliuiqxabfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_2PGpbqPSgnXYDEB74EEzCg_fNG-ZHt1";
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const quests=[{title:"Check a store display",biz:"Example business",reward:"$3.00",time:"3 min",icon:"📸",tag:"Nearby"},{title:"Answer a short survey",biz:"Example business",reward:"$1.25",time:"1 min",icon:"📝",tag:"Online"},{title:"Verify business hours",biz:"Example business",reward:"$1.75",time:"2 min",icon:"🕐",tag:"Nearby"},{title:"Find a product on a shelf",biz:"Example business",reward:"$4.00",time:"5 min",icon:"🛒",tag:"Nearby"}];
let authMode="signup";
function render(){document.getElementById("questList").innerHTML=quests.map(q=>`<article class="card"><div class="cardtop"><span class="icon">${q.icon}</span><span class="tag">${q.tag}</span></div><h3>${q.title}</h3><p class="biz">${q.biz}</p><div class="meta"><span>⏱ ${q.time}</span><strong>${q.reward}</strong></div><button class="example" onclick="alert('This is an example quest. Real paid quests will appear after CashQuest launches its account, payment and verification systems.')">Example — not claimable yet</button></article>`).join("")}
function showTab(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.getElementById(id).classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
function openAuth(){document.getElementById("authModal").classList.add("open");document.getElementById("authModal").setAttribute("aria-hidden","false");setAuthStatus("")}
function closeAuth(){document.getElementById("authModal").classList.remove("open");document.getElementById("authModal").setAttribute("aria-hidden","true")}
function setAuthStatus(msg){document.getElementById("authStatus").textContent=msg}
function toggleAuthMode(){authMode=authMode==="signup"?"signin":"signup";document.getElementById("authTitle").textContent=authMode==="signup"?"Create your account":"Welcome back";document.getElementById("authNote").textContent=authMode==="signup"?"Join CashQuest to prepare for the live marketplace.":"Sign in to your CashQuest account.";document.getElementById("authSubmit").textContent=authMode==="signup"?"Create account":"Sign in";document.getElementById("authSwitch").textContent=authMode==="signup"?"Already have an account? Sign in":"Need an account? Create one";document.getElementById("authPassword").setAttribute("autocomplete",authMode==="signup"?"new-password":"current-password");setAuthStatus("")}
document.getElementById("authForm").addEventListener("submit",async e=>{e.preventDefault();const email=document.getElementById("authEmail").value.trim();const password=document.getElementById("authPassword").value;setAuthStatus("Working…");document.getElementById("authSubmit").disabled=true;try{if(authMode==="signup"){const {data,error}=await supabaseClient.auth.signUp({email,password});if(error)throw error;if(data.user){await supabaseClient.from("profiles").upsert({id:data.user.id,display_name:email.split("@")[0],role:"worker"},{onConflict:"id"});}setAuthStatus("Account created. Check your email to confirm your address, then sign in.");}else{const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error;setAuthStatus("Signed in!");setTimeout(closeAuth,700);updateAuthButton();}}catch(err){setAuthStatus(err.message||"Something went wrong.")}finally{document.getElementById("authSubmit").disabled=false}});
async function updateAuthButton(){const {data}=await supabaseClient.auth.getUser();const b=document.getElementById("authButton");if(data.user){b.textContent="Account";b.onclick=()=>alert("Signed in as "+data.user.email+" — account dashboard coming next.")}else{b.textContent="Sign in / Join";b.onclick=openAuth}}
supabaseClient.auth.onAuthStateChange(()=>updateAuthButton());updateAuthButton();render();