-- CashQuest initial database schema
-- Run this in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'worker' check (role in ('worker','business','admin')),
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;
create policy "Users can read own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create table if not exists public.quests (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  reward_cents integer not null check (reward_cents >= 0),
  status text not null default 'draft' check (status in ('draft','active','paused','completed')),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);
alter table public.quests enable row level security;
create policy "Anyone can read active quests" on public.quests for select using (status = 'active' or auth.uid() = created_by);
